### ISSUE TITLE
Having a problem running benchmark problems

### ISSUE THREAD

**Issue by hojjatks** [ablancha/gpsearch#2] opened 2023-02-21 01:05 UTC
Hi
I would like to first to thank for sharing your code.
When I run the benchmark problem (extreme event one in the Journal of Computational physics) there is an error in the program. Some of the acquisation functions work but there is an error with some other ones. 
I have copied the error message here:

PCA Eigenvalues: [0.24774016 0.04405693]
Benchmarking EI
[Parallel(n_jobs=40)]: Using backend LokyBackend with 40 concurrent workers.
[Parallel(n_jobs=40)]: Done   5 tasks      | elapsed:  1.8min
[Parallel(n_jobs=40)]: Done  18 tasks      | elapsed:  1.9min
[Parallel(n_jobs=40)]: Done  32 out of 100 | elapsed:  2.0min remaining:  4.3min
[Parallel(n_jobs=40)]: Done  43 out of 100 | elapsed:  3.7min remaining:  4.9min
[Parallel(n_jobs=40)]: Done  54 out of 100 | elapsed:  3.8min remaining:  3.2min
[Parallel(n_jobs=40)]: Done  65 out of 100 | elapsed:  3.9min remaining:  2.1min
[Parallel(n_jobs=40)]: Done  76 out of 100 | elapsed:  4.0min remaining:  1.3min
[Parallel(n_jobs=40)]: Done  87 out of 100 | elapsed:  5.4min remaining:   48.0s
[Parallel(n_jobs=40)]: Done  98 out of 100 | elapsed:  5.5min remaining:    6.7s
Benchmarking PI
[Parallel(n_jobs=40)]: Done 100 out of 100 | elapsed:  5.5min finished
[Parallel(n_jobs=40)]: Using backend LokyBackend with 40 concurrent workers.
[Parallel(n_jobs=40)]: Done   5 tasks      | elapsed:  1.9min
[Parallel(n_jobs=40)]: Done  18 tasks      | elapsed:  1.9min
[Parallel(n_jobs=40)]: Done  32 out of 100 | elapsed:  2.0min remaining:  4.3min
[Parallel(n_jobs=40)]: Done  43 out of 100 | elapsed:  3.7min remaining:  5.0min
[Parallel(n_jobs=40)]: Done  54 out of 100 | elapsed:  3.9min remaining:  3.3min
[Parallel(n_jobs=40)]: Done  65 out of 100 | elapsed:  4.0min remaining:  2.1min
[Parallel(n_jobs=40)]: Done  76 out of 100 | elapsed:  4.1min remaining:  1.3min
[Parallel(n_jobs=40)]: Done  87 out of 100 | elapsed:  5.4min remaining:   48.8s
[Parallel(n_jobs=40)]: Done  98 out of 100 | elapsed:  5.6min remaining:    6.8s
Benchmarking LCB
[Parallel(n_jobs=40)]: Done 100 out of 100 | elapsed:  5.6min finished
[Parallel(n_jobs=40)]: Using backend LokyBackend with 40 concurrent workers.
[Parallel(n_jobs=40)]: Done   5 tasks      | elapsed:  2.5min
[Parallel(n_jobs=40)]: Done  18 tasks      | elapsed:  2.7min
[Parallel(n_jobs=40)]: Done  32 out of 100 | elapsed:  2.8min remaining:  5.9min
[Parallel(n_jobs=40)]: Done  43 out of 100 | elapsed:  5.1min remaining:  6.7min
[Parallel(n_jobs=40)]: Done  54 out of 100 | elapsed:  5.3min remaining:  4.5min
[Parallel(n_jobs=40)]: Done  65 out of 100 | elapsed:  5.5min remaining:  2.9min
[Parallel(n_jobs=40)]: Done  76 out of 100 | elapsed:  5.6min remaining:  1.8min
[Parallel(n_jobs=40)]: Done  87 out of 100 | elapsed:  7.3min remaining:  1.1min
[Parallel(n_jobs=40)]: Done  98 out of 100 | elapsed:  7.6min remaining:    9.3s
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/benchmarker.py", line 107, in optimization_loop
    m_list = o.optimize(n_iter, acquisition,
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/core/optimaldesign.py", line 165, in optimize
    self.model.optimize_restarts(**kwargs_GPy)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/model.py", line 182, in optimize_restarts
    raise e
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/model.py", line 172, in optimize_restarts
    self.optimize(**kwargs)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/GPy/core/gp.py", line 675, in optimize
    ret = super(GP, self).optimize(optimizer, start, messages, max_iters, ipython_notebook, clear_after_finish, **kwargs)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/model.py", line 113, in optimize
    self.optimizer_array = opt.x_opt
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/parameterized.py", line 339, in __setattr__
    return object.__setattr__(self, name, val)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/core/parameter_core.py", line 124, in optimizer_array
    self.trigger_update()
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/core/updateable.py", line 79, in trigger_update
    self._trigger_params_changed(trigger_parent)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/core/parameter_core.py", line 134, in _trigger_params_changed
    self.notify_observers(None, None if trigger_parent else -np.inf)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/core/observable.py", line 91, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/core/observable.py", line 91, in <listcomp>
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/paramz/core/parameter_core.py", line 508, in _parameters_changed_notification
    self.parameters_changed()
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/GPy/core/gp.py", line 274, in parameters_changed
    self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.likelihood, self.Y_normalized, self.mean_function, self.Y_metadata)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/GPy/inference/latent_function_inference/exact_gaussian_inference.py", line 58, in inference
    Wi, LW, LWi, W_logdet = pdinv(Ky)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/GPy/util/linalg.py", line 207, in pdinv
    L = jitchol(A, *args)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/GPy/util/linalg.py", line 75, in jitchol
    raise linalg.LinAlgError("not positive definite, even with jitter.")
numpy.linalg.LinAlgError: not positive definite, even with jitter.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/precursor/run_benchmark.py", line 68, in <module>
    main()

  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/precursor/run_benchmark.py", line 64, in main
    result = b.run_benchmark(n_trials, n_jobs, filename=prefix+acq)

  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/benchmarker.py", line 71, in run_benchmark
    res = self._run_benchmark(n_trials, n_jobs=n_jobs)

  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/benchmarker.py", line 79, in _run_benchmark
    x = Parallel(n_jobs=n_jobs, backend="loky", verbose=10) \

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 938, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)

  File "/home/hkaveh/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()

  File "/home/hkaveh/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception

LinAlgError: not positive definite, even with jitter.

**Comment by ablancha** [comment] 2023-02-23 11:52
This is an issue internal to GPy.  It's not able to do the Cholesky decomposition, which might happen when the K matrix is close to singular.  Could you share your environment?  Thanks!

**Comment by hojjatks** [comment] 2023-02-23 19:10
Thanks for the response. I am simulating the benchmark problem (extreme event) in the paper. 
I use python 3.9 and GPy version 1.10.0.
I noticed that you have written that I should use deploy branch of GPy. Can you clarify how can I do that?

**Comment by ablancha** [comment] 2023-02-26 23:06
Could you try downgrading GPy to version 1.9.9 and see if the issue persists?

To use the deploy branch, you can try something like 

```
git clone https://github.com/SheffieldML/GPy.git
cd GPy
git checkout deploy
python setup.py build_ext --inplace
```

I'll look into compatibility with version 1.10.0 in the next few days.

**Comment by hojjatks** [comment] 2023-02-28 03:10
I tried to downgrade GPy to version 1.9.9. The older version of GPy does not work with current version of numpy (NumPy 1.24.1). I downgraded numpy as well but it did not work. The error is different now and I guess it is because of incompatibility of different versions of packages that are being used. 
Is there something that we can do to make the code with the update version of GPy?
Can you let me know which version of different packages are you using?

**Comment by hojjatks** [comment] 2023-02-28 04:51
I fixed the problem with GPy version1.10.0. 
Simulating the same program I see another error which I have copied here. This error happens when I use the following acquisition function:
LCB_LW, IVR_LW and IVR_LWBO.
One example of the error is the following:
Benchmarking IVR_LWBO
[Parallel(n_jobs=40)]: Using backend LokyBackend with 40 concurrent workers.
[Parallel(n_jobs=40)]: Done   5 tasks      | elapsed:    2.5s
[Parallel(n_jobs=40)]: Done  18 tasks      | elapsed:    2.7s
[Parallel(n_jobs=40)]: Done  32 out of 100 | elapsed:    2.7s remaining:    5.7s
[Parallel(n_jobs=40)]: Done  43 out of 100 | elapsed:    2.7s remaining:    3.6s
[Parallel(n_jobs=40)]: Done  54 out of 100 | elapsed:    2.7s remaining:    2.3s
[Parallel(n_jobs=40)]: Done  65 out of 100 | elapsed:    2.7s remaining:    1.4s
[Parallel(n_jobs=40)]: Done  76 out of 100 | elapsed:    2.7s remaining:    0.8s
[Parallel(n_jobs=40)]: Done  87 out of 100 | elapsed:    2.7s remaining:    0.4s
[Parallel(n_jobs=40)]: Done  98 out of 100 | elapsed:    2.7s remaining:    0.1s
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/benchmarker.py", line 107, in optimization_loop
    m_list = o.optimize(n_iter, acquisition,
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/core/optimaldesign.py", line 132, in optimize
    acq = check_acquisition(acquisition, self.model, self.inputs)
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/core/acquisitions/check_acquisition.py", line 54, in check_acquisition
    return IVR_LWBO(model, inputs)
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/core/acquisitions/bo.py", line 77, in __init__
    super().__init__(model, inputs, likelihood=likelihood)
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/core/acquisitions/base.py", line 75, in __init__
    likelihood = Likelihood(model, inputs)
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/core/likelihood.py", line 50, in __init__
    self._prepare_likelihood()
  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/core/likelihood.py", line 162, in _prepare_likelihood
    x, y = custom_KDE(mu, weights=fx).evaluate()
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/KDEpy/FFTKDE.py", line 145, in evaluate
    raise ValueError("The bw must be a number.")
ValueError: The bw must be a number.
"""


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/precursor/run_benchmark.py", line 78, in <module>
    main()

  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/precursor/run_benchmark.py", line 74, in main
    result = b.run_benchmark(n_trials, n_jobs, filename=prefix+acq)

  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/benchmarker.py", line 71, in run_benchmark
    res = self._run_benchmark(n_trials, n_jobs=n_jobs)

  File "/home/hkaveh/Research/MechanismOfExtremeEvents/Codes/TheoriticalSystems/gpsearch-master/gpsearch/benchmarks/benchmarker.py", line 79, in _run_benchmark
    x = Parallel(n_jobs=n_jobs, backend="loky", verbose=10) \

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 938, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)

  File "/home/hkaveh/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()

  File "/home/hkaveh/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception

ValueError: The bw must be a number.

**Comment by ablancha** [comment] 2023-03-02 01:03
Try adding `.item()` in Line 185 of `compute_KDE`:
```
bw = np.sqrt(sc.covariance).flatten().item()
```
(You can probably get rid of `flatten` in that case.)

**Comment by hojjatks** [comment] 2023-03-04 00:43
Thanks for your response.
I still get the following error:

  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/home/hkaveh/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
    AttributeError: 'NoneType' object has no attribute 'split'

**Comment by ablancha** [comment] 2023-03-10 11:58
That last error is from joblib, not gpsearch.  I still suspect there may be something wrong with your environment.  I just created a fresh conda environment with Python 3.7 (see updated `README` instructions) and am not able to reproduce any of the above issues.  So I would suggest trying the same.  Please let me know if this solves the problem.

**Comment by ablancha** [comment] 2023-03-21 21:08
Any update on this?  I'll close the issue if everything is working.

**Comment by hojjatks** [comment] 2023-03-21 21:22
Could you please give me more time?
thanks

**Comment by hojjatks** [comment] 2023-03-31 01:23
Dear Antoine 
Thank you for the updated readme instructions. The code now works.

**Comment by ablancha** [comment] 2023-03-31 11:37
Great, thanks!

**Closed as completed by ablancha** 2023-03-31 11:37 UTC
